Fix 'undefined reference to AO_pt_lock' if configure is using clang-16
Issue #57 (libatomic_ops)

Place addition of -Werror to CFLAGS (if requested) in configure.ac
after AC_CHECK_LIB(pthread), otherwise clang-16 turns the warning
about a missing void in pthread_self declaration (as generated by
autoconf-2.71) into an error, thus causing the AC_CHECK_LIB to fail
(leaving have_pthreads variable set to false).

* configure.ac (werror): Move to be after AC_CHECK_LIB; add comment.
* configure.ac [$enable_werror=yes && $GCC=yes] (CFLAGS): Likewise.