Fix 'undefined reference to __atomic_load/store/cas_16' Mingw64-gcc error (fix of commit 759fa976)
Issue #34 (libatomic_ops).

gcc/x64 (as of gcc-12.2, including that of mingw64) requires -latomic
flag in case of double-word atomic operations use.

* src/atomic_ops/sysdeps/gcc/x86.h [!AO_DISABLE_GCC_ATOMICS
&& !__APPLE_CC__ && !__clang__ && !AO_PREFER_BUILTIN_ATOMICS
&& !AO_THREAD_SANITIZER] (AO_SKIPATOMIC_double_compare_and_swap_ANY,
AO_SKIPATOMIC_DOUBLE_LOAD_STORE_ANY): Define only if __x86_64__;
define regardless of __MINGW32__ and gcc version; update comment.